event-app/lib/eventapp_web/router.ex
defmodule EventappWeb.Router do
  use EventappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventappWeb.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventappWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/photo", UserController, :photo
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  scope "/api", EventappWeb do
     pipe_through :api
     resources "/votes", VoteController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventappWeb.Telemetry
    end
  end
end

event-app/lib/eventapp_web/templates/page/index.html.eex
<%= if have_current_user?(@conn) do %>
<p>
  <%= link "New Event", to: Routes.event_path(@conn, :new), class: "btn-lg font-weight-bold btn btn-info"%>
  <%= link "Check All Available Users", to: Routes.user_path(@conn, :index), class: "ml-5 font-weight-bold text-info"%>
</p>

<div class="events-container">
  <%= for event <- @events do %>
  <%= if current_user_is?(@conn, event.user_id) || invited(@conn, event.user_id) do %>
  <div class="card mt-4 event-card" data-event-id="<%= event.id %>">
    <div class="card-body">
      <p class="card-text font-weight-bold h4">
        <img src="<%= Routes.user_path(@conn, :photo, event.user) %>"
        alt=""
        height=50 width=50>
        <%= link event.user.name, to: Routes.user_path(@conn, :show, event)%>
      </p>
      <div class="h1"><%= link event.name, to: Routes.event_path(@conn, :show, event), class: "mr-2 font-weight-bold text-info" %></div>
      <h5 class="card-text h4-small"><%= event.date %></h5>
      <p class="card-text font-weight-bold h4"><%= event.description %></p>
      <%= if current_user_is?(@conn, event.user_id) do %>
      <%= link "Edit", to: Routes.event_path(@conn, :edit, event), class: "mr-2 font-weight-bold btn btn-info"%>
      <%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"], class: "mr-2 font-weight-bold btn btn-danger"%>
      <%= end %>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
<% else %>
<h1>Login or Register An Account To Start Show Events</h1>
<% end %>