event-app/lib/eventapp_web/router.ex
defmodule EventappWeb.Router do
  use EventappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventappWeb.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventappWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/photo", UserController, :photo
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  scope "/api", EventappWeb do
     pipe_through :api
     resources "/votes", VoteController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventappWeb.Telemetry
    end
  end
end

event-app/lib/eventapp/comments.ex
defmodule Eventapp.Comments do
  @moduledoc """
  The Comments context.
  """

  import Ecto.Query, warn: false
  alias Eventapp.Repo

  alias Eventapp.Comments.Comment

  @doc """
  Returns the list of comments.

  ## Examples

      iex> list_comments()
      [%Comment{}, ...]

  """
  def list_comments do
    Repo.all(Comment)
  end

  @doc """
  Gets a single comment.

  Raises `Ecto.NoResultsError` if the Comment does not exist.

  ## Examples

      iex> get_comment!(123)
      %Comment{}

      iex> get_comment!(456)
      ** (Ecto.NoResultsError)

  """
  def get_comment!(id), do: Repo.get!(Comment, id)

  @doc """
  Creates a comment.

  ## Examples

      iex> create_comment(%{field: value})
      {:ok, %Comment{}}

      iex> create_comment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a comment.

  ## Examples

      iex> update_comment(comment, %{field: new_value})
      {:ok, %Comment{}}

      iex> update_comment(comment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a comment.

  ## Examples

      iex> delete_comment(comment)
      {:ok, %Comment{}}

      iex> delete_comment(comment)
      {:error, %Ecto.Changeset{}}

  """
  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking comment changes.

  ## Examples

      iex> change_comment(comment)
      %Ecto.Changeset{data: %Comment{}}

  """
  def change_comment(%Comment{} = comment, attrs \\ %{}) do
    Comment.changeset(comment, attrs)
  end
end

event-app/lib/eventapp/comments/comment.ex
defmodule Eventapp.Comments.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :body, :string
    field :vote, :integer
    belongs_to :event, Eventapp.Events.Event
    belongs_to :user, Eventapp.Users.User

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:body, :vote, :event_id, :user_id])
    |> validate_required([:body, :vote, :event_id, :user_id])
  end
end

event-app/lib/eventapp_web/controllers/comment_controller.ex
defmodule EventappWeb.CommentController do
  use EventappWeb, :controller

  alias Eventapp.Comments
  alias Eventapp.Comments.Comment

  def index(conn, _params) do
    comments = Comments.list_comments()
    render(conn, "index.html", comments: comments)
  end

  def new(conn, _params) do
    changeset = Comments.change_comment(%Comment{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"comment" => comment_params}) do
    comment_params = comment_params
    |> Map.put("user_id", current_user_id(conn))
    case Comments.create_comment(comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, comment.event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    render(conn, "show.html", comment: comment)
  end

  def edit(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    changeset = Comments.change_comment(comment)
    render(conn, "edit.html", comment: comment, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}) do
    comment = Comments.get_comment!(id)

    case Comments.update_comment(comment, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, comment.event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    {:ok, _comment} = Comments.delete_comment(comment)
    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :show, comment.event_id))
  end
end

event-app/lib/eventapp_web/views/comment_view.ex
defmodule EventappWeb.CommentView do
  use EventappWeb, :view
end

event-app/lib/eventapp_web/templates/comment/edit.html.eex
<div class="font-weight-bold h3 form-inline my-4">
  <img src="<%= Routes.user_path(@conn, :photo, @comment.user_id) %>"
  alt="" height=60 width=60 class="mr-3">
  <%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :update, @comment)) %>
</div>

event-app/lib/eventapp_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
  <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>


<%= textarea f, :body, cols: 90, rows: 1, class: "form-control ml-3"%>
<%= error_tag f, :body %>
<%= hidden_input f, :vote%>
<%= hidden_input f, :event_id %>

<%= submit "Comment", class: "btn btn-lg btn-primary mr-2 font-weight-bold"%>
<% end %>

event-app/lib/eventapp_web/templates/comment/index.html.eex
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Vote</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.body %></td>
      <td><%= comment.vote %></td>

      <td>
        <span><%= link "Show", to: Routes.comment_path(@conn, :show, comment) %></span>
        <span><%= link "Edit", to: Routes.comment_path(@conn, :edit, comment) %></span>
        <span><%= link "Delete", to: Routes.comment_path(@conn, :delete, comment), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Comment", to: Routes.comment_path(@conn, :new) %></span>

event-app/lib/eventapp_web/templates/comment/new.html.eex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :create)) %>

event-app/lib/eventapp_web/templates/comment/show.html.eex
<h1>Show Comment</h1>

<ul>

  <li>
    <strong>Body:</strong>
    <%= @comment.body %>
  </li>

  <li>
    <strong>Vote:</strong>
    <%= @comment.vote %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.comment_path(@conn, :edit, @comment) %></span>
<span><%= link "Back", to: "/" %></span>